config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :food_journals
  resources :layouts
  root "users#index"
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'

  get '/about', :to => redirect('/about.html')

  get ':action' => 'static#:action'

end

app/models/food_journal.rb
class FoodJournal < ActiveRecord::Base
  belongs_to :user

  validates :food, presence: true
  validates :qty, presence: true
end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :food_journals

  validates_uniqueness_of :handle
  validates_length_of :handle, :minimum => 3
  validates :handle, presence: true
  validates :password, length: {
    minimum:3,
    maximum:15,
    too_short: "Please make a password that is greater than 3 characters.",
    too_short: "Please make a password that is shorter."
  }
  validates :age, presence: true
  validates :weight , presence: true
  validates :target, presence: true
  validates :height, presence: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_journals_controller.rb
class FoodJournalsController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  skip_before_filter  :verify_authenticity_token
  require 'httparty'

  def index

    @display_date = Date.parse(params[:date]).strftime("%m/%d/%Y")
    @the_date = Date.parse(params[:date])
    @user = User.find_by(id: session[:user_id])
    @foods = @user.food_journals.where(date: @the_date.beginning_of_day..@the_date.end_of_day)

  end


  def show
    def send_simple_message
    RestClient.post "https://api:key-45353bea761148676ae6fbb927af15b5"\
    "@api.mailgun.net/v2/sandbox471d5fcdac604d1baef1aac24fbe0849.mailgun.org/messages",
    :from => "Mailgun Sandbox <postmaster@sandbox471d5fcdac604d1baef1aac24fbe0849.mailgun.org>",
    :to => "Kyle Hogan <kylehogan1980@yahoo.com>",
    :subject => "Hello from DropBox test",
    :text => "Congratulations Kyle Hogan, you just sent an email with Mailgun!  You are truly awesome!  You can see a record of this email in your logs: https://mailgun.com/cp/log .  You can send up to 300 emails/day from this sandbox server.  Next, you should add your own domain so you can send 10,000 emails/month for free."
    end

    urlOne = "https://api.nutritionix.com/v1_1/search/";
    urlTwo = "?item_type=3&results=0%3A20&cal_min=0&cal_max=5000&fields=item_name%2Cnf_dietary_fiber%2Cbrand_name%2Cnf_calories%2Cnf_serving_size_qty%2Cnf_serving_size_unit%2Cnf_total_fat%2Cnf_total_carbohydrate%2Cnf_protein%2Cnf_serving_weight_grams%2Citem_id%2Cbrand_id&appId=bdcc47ce&appKey=e53cc81b43727bf30f6ffb0a54ab80a8"
    instaURL = "https://api.instagram.com/v1/tags/food/media/recent?client_id=8fe4db31e3a940068664c1e7e3c5c061"
    food = (params[:food])
    # foodsNutrix = HTTParty.get(instaURL)
    foodsNutrix = HTTParty.get(urlOne + URI.encode(food) + urlTwo)
    @user = User.find_by(session[:user_id])
    @foods = @user.food_journals

		    respond_to do |format|

	         format.json { render json: foodsNutrix }

	     end

  end


  def destroy
    @food = FoodJournal.find_by(id: params[:id])
    @food.destroy

    if params[:date] != ''
      @the_date = Date.parse(params[:date])
      redirect_to '/food_journals?date=' + @the_date.to_s
    else
      redirect_to edit_user_path
    end
  end





  def create

    @food = FoodJournal.create(food_params)
    if @food.save

      if params[:date]
        @food.update(date: Date.parse(params[:date]).noon)
        @foods = FoodJournal.where(:user_id => session[:user_id], date: Date.parse(params[:date]).beginning_of_day..Date.parse(params[:date]).end_of_day)
        render :file => "layouts/_food", :layout => false
        # redirect_to '/food_journals?date=' + Date.parse(params[:date]).to_s
      else
        @the_date = Date.today
        @food.update(date: @the_date)
        @foods = FoodJournal.where(:user_id => session[:user_id], date: Date.today.beginning_of_day..Date.today.end_of_day)
        render :file => "layouts/_food", :layout => false
      end

    else
      @foods = FoodJournal.where(:user_id => session[:user_id], date: Date.today.beginning_of_day..Date.today.end_of_day)
      render :file => "layouts/_food", :layout => false

    end
  end

  def edit
    @user = User.find_by(id: session[:user_id])
    @food = FoodJournal.find_by(id: params[:id])
    @foods = [@food]
  end


  private
    def food_params
      params.require(:food_journal).permit(:food , :qty, :cals, :fat, :carbs, :protein, :user_id ,)
    end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    redirect_to '/'
  end

  def create
    @user = User.find_by(handle: params[:username])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to new_user_path
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController



def contact


  render :contact

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def show
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      @foods = @user.food_journals
    end
  end

  def index
    @user = User.find_by(id: session[:user_id])
    @foods = FoodJournal.where(:user_id => session[:user_id], date: Date.today.beginning_of_day..Date.today.end_of_day) if @user
    @the_date = Date.today;
    render :index

  end


  def new
    if session[:user_id]
      redirect_to '/'
    end
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end





  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to new_user_path
  end


  def edit
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      @foods = @user.food_journals
    else
      redirect_to '/'
    end
  end

  def update
    @user = User.find_by(id: session[:user_id])
    @user.update(user_params)
    redirect_to edit_user_path(@user)
  end


  private
    def user_params
      params.require(:user).permit(:handle, :email, :password, :male , :age , :weight, :target, :height, :goal)
    end



end

#
# users GET    /users(.:format)                  users#index
#             POST   /users(.:format)                  users#create
#    new_user GET    /users/new(.:format)              users#new
#   edit_user GET    /users/:id/edit(.:format)         users#edit
#        user GET    /users/:id(.:format)              users#show
#             PATCH  /users/:id(.:format)              users#update
#             PUT    /users/:id(.:format)              users#update
#             DELETE /users/:id(.:format)              users#destroy
# food_journals GET    /food_journals(.:format)          food_journals#index
#             POST   /food_journals(.:format)          food_journals#create
# new_food_journal GET    /food_journals/new(.:format)      food_journals#new
# edit_food_journal GET    /food_journals/:id/edit(.:format) food_journals#edit
# food_journal GET    /food_journals/:id(.:format)      food_journals#show
#             PATCH  /food_journals/:id(.:format)      food_journals#update
#             PUT    /food_journals/:id(.:format)      food_journals#update
#             DELETE /food_journals/:id(.:format)      food_journals#destroy
#        root GET    /                                 users#index
#    register GET    /register(.:format)               users#new
#     session POST   /session(.:format)                session#create
#             DELETE /session(.:format)                session#destroy

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_journals/edit.html.erb
<div id="foodReceived">

<%= render "layouts/food" %>

</div>

app/views/food_journals/index.html.erb
<h2>Food Journal for <%= @the_date.strftime("%m/%d/%Y") %> </h2>
<br>

<%= link_to 'PREVIOUS DAY',  food_journals_path + '?date=' + @the_date.prev_day.to_s%> |
<%= link_to 'NEXT DAY',  food_journals_path + '?date=' + @the_date.next_day.to_s%> |
<%= link_to 'HOME',  "/" %>
<br>
<div id="foodReceived">
<%= render "layouts/food" %>
</div>
<br>
<br>



<div id="side">


    <input id="foodToFind" placeholder="food item"/>
      <button id="get"> SEARCH</button>
  <div id="menuContainer">
    <ul id="menu">

    </ul>
  </div>



</div>
<div>

<span>Amount in grams</span><input type="number" id="qty" placeholder="0" min="1">
<button id="create">add food to diary</button></div>
<div id="nutrionalInfo">
</div>





<!-- <input id="foodToFind" placeholder="food item"/>
  <button id="get"> Find </button>
  <div id="menuContaier">
    <ul id="menu">

    </ul>

  </div>
<br>

<div id="nutrionalInfo">

</div>
Amount in grams<input type="number" id="qty" placeholder="0" min="0">
<button id="create">click to add this food to your diary</button>
</div> -->


<br>
<span id="dateSpan"><%= @the_date%></span>

app/views/food_journals/junk.html.erb
<em>session new.html.erb</em>

<form action = "/session" method = "POST">
  <label for = "username">
    Username
  </label>
  <input name = "username" type = "text">
  <label for = "password">
    Password:
  </label>
  <input name = "password" type = "password">
  <input name = "authenticity_token" value = "<%= form_authenticity_token() %>"
    type = "hidden">
<button>Sign In</button>
</form>
<br>

Register New User

<%= form_for @user, url: {action: 'create'} do |f|%>
  <%= f.label :username%>
  <%= f.text_field :handle%>
  <br>
  <%= f.label :password%>
  <%= f.password_field :password%>
  <br>
  <%= f.label :confirm_password%>
  <%= f.password_field :confirm_password%>
  <br>
  <%= radio_button_tag(:male, true) %>
  <%= label_tag(:gender_male, "Male")%>
  <%= radio_button_tag(:male, false) %>
  <%= label_tag(:gender_male, "Female")%>
  <br>
  <%= f.label :age%>
  <%= f.number_field :age%>
  <br>
  <%= f.label :weight%>
  <%= f.number_field :weight%>
  <br>
  <%= f.submit %>
<% end %>

<form action = "/session" method = "POST">
  <label for = "username">
    Username
  </label>
  <input name = "username" type = "text">
  <label for = "password">
    Password:
  </label>
  <input name = "password" type = "password">
  male:<input type="radio" name="male" value="true">
  female:<input type="radio" name="male" value="false">
  <lable for = "weight">
    Weight:
  </lable>
  <input name = "weight" type = "number" min="0">
  <lable for = "age">
    Age:
  </lable>
  <input name = "age" type = "number" min="0">
  <input name = "authenticity_token" value = "<%= form_authenticity_token() %>"
    type = "hidden">
<button>Sign In</button>
</form>

app/views/layouts/_food.html.erb
<div id="foods">
  <table class="gridtable">

  <tr>
    <th>
      Food Item
    </th>
    <th>
      Serving in grams
    </th>
    <th>
      Calories
    </th>
    <th>
      Calories from Fat
    </th>
    <th>
      Calories from Protein
    </th>
    <th>
      Calories from Carbs
    </th>

  </tr>
  <%

  total_cals = 0
  total_fat = 0
  total_pro = 0
  total_carbs = 0
  if @foods
  @foods.each do |food|

    total_cals += food.cals
    total_fat = total_fat + food.fat
    total_carbs = total_carbs + food.carbs
    total_pro = total_pro + food.protein %>
    <tr>
      <td>
        <%=food.food%>
      </td>
      <td>
        <%= food.qty %>
      </td>
      <td>
        <%= food.cals %>
      </td>
      <td>
        <%= food.fat %>
      </td>
      <td>
        <%= food.protein %>
      </td>
      <td>
        <%= food.carbs %>
      </td>

      <td>
        <%= link_to 'delete entry' , food_journal_path(food) + '?date=' + @the_date.to_s , method: :delete %>
      </td>
    </tr>



  <% end
end%>
  <tr>
    <td>

    </td>
    <td>

    </td>
    <td>

    </td>
    <td>

    </td>
    <td>

    </td>
    <td>

    </td>
  </tr>
  <br>

    <tr>
      <td>

      </td>
      <td>

      </td>
      <th>
        Total Calories
      </th>
      <th>
        Total Calories from Fat
      </th>
      <th>
        Total Calories from Protein
      </th>
      <th>
        Total Calories from Carbs
      </th>
    </tr>
    <tr>
      <td>

      </td>
      <td>

      </td>
      <td>
        <%=total_cals%>
      </td>
      <td>
        <%=total_fat%>
      </td>
      <td>
        <%=total_pro%>
      </td>
      <td>
        <%=total_carbs%>
      </td>
    </tr>

  </table>
  <br>
<script charset="utf-8">


  <%
  total_cals = 0
  total_fat_cals = 0
  total_carb_cals = 0
  total_pro_cals = 0
  if @foods
    @foods.each do |food|
      total_fat_cals += food.fat
      total_carb_cals += food.carbs
      total_pro_cals += food.protein
      total_cals += food.cals
    end
  end
  %>
  var calPie = [0,0,0,100];
  <%if total_cals > 0 %>
  calPie = [<%= total_pro_cals %>,<%= total_carb_cals %>,<%= total_fat_cals %>];
  <% end %>
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journal</title>
  <script src="http://d3js.org/d3.v3.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <script>
  <% if @user %>

  var user = <%= @user.id %>;

  <% end %>

  </script>

</head>

<body>

  <div id="header">

    <div id>
<% if session[:user_id] && @user %>
  <span id="user">User: <%= @user.handle %></span><br>
  <%= link_to 'Profile', edit_user_path(@user) if @user%><br>
  <%= link_to 'Food Diary', food_journals_path + '?date=' + Date.today.to_s if @user %>


    <form method="POST" action="/session">
      <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
      <input name="_method" value="DELETE" type="hidden">
  <button>Sign Out</button>
  </div>
  <br>
  </form>
<% else %>
  Already a member?<br>



    <form action = "/session" method = "POST">

          <!-- <label for = "username">
            Username:
          </label> -->

        <input name = "username" type = "text" placeholder = "username">

        <!-- <label for = "password">
          Password:
        </label> -->

        <input name = "password" type = "password" placeholder = "password">
        <input name = "authenticity_token" value = "<%= form_authenticity_token() %>"
          type = "hidden">

        <button>Sign In</button><br>

  </form>
  <%= link_to 'Register a new user', new_user_path %>
</div>
<% end %>

<div id="title">

<span>FOOD IN GRAMS</span>

</div>

</div>
<div id="seperate">

</div>
<hr>
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/session/new.html.erb
<em>session new.html.erb</em>

<form action = "/session" method = "POST">
  <label for = "username">
    Username
  </label>
  <input name = "username" type = "text">
  <label for = "password">
    Password:
  </label>
  <input name = "password" type = "password">
  <input name = "authenticity_token" value = "<%= form_authenticity_token() %>"
    type = "hidden">
<button>Sign In</button>
</form>
<br>

Register New User

<%= form_for @user, url: {action: 'create'} do |f|%>
  <%= f.label :username%>
  <%= f.text_field :handle%>
  <br>
  <%= f.label :password%>
  <%= f.password_field :password%>
  <br>
  <%= f.label :confirm_password%>
  <%= f.password_field :confirm_password%>
  <br>
  <%= radio_button_tag(:male, true) %>
  <%= label_tag(:gender_male, "Male")%>
  <%= radio_button_tag(:male, false) %>
  <%= label_tag(:gender_male, "Female")%>
  <br>
  <%= f.label :age%>
  <%= f.number_field :age%>
  <br>
  <%= f.label :weight%>
  <%= f.number_field :weight%>
  <br>
  <%= f.submit %>
<% end %>

<form action = "/session" method = "POST">
  <label for = "username">
    Username
  </label>
  <input name = "username" type = "text">
  <label for = "password">
    Password:
  </label>
  <input name = "password" type = "password">
  male:<input type="radio" name="male" value="true">
  female:<input type="radio" name="male" value="false">
  <lable for = "weight">
    Weight:
  </lable>
  <input name = "weight" type = "number" min="0">
  <lable for = "age">
    Age:
  </lable>
  <input name = "age" type = "number" min="0">
  <input name = "authenticity_token" value = "<%= form_authenticity_token() %>"
    type = "hidden">
<button>Sign In</button>
</form>

app/views/users/edit.html.erb
<script>
var user = <%= @user.id %>;
</script>

<%= form_for @user, url: {action: 'update'} do |f|%>

  <table>

  <tr>


    <td><%= f.label :username%></td>
    <td><%= f.text_field :handle%></td>

  </tr>
<tr>

    <td><%= f.radio_button(:male, true) %>
    <%= f.label(:gender_male, "Male")%></td>
    <td><%= f.radio_button(:male, false) %>
    <%= f.label(:gender_male, "Female")%></td>
  </tr><tr>

    <td><%= f.label :age%></td>
    <td><%= f.number_field :age%></td>
  </tr><tr>

    <td><%= f.label :weight%></td>
    <td><%= f.number_field :weight%></td>
  </tr><tr>

    <td><%= f.label :target_calories%></td>
    <td><%= f.number_field :target%></td>
  </tr><tr>

    <td><%= f.label :height_in_inches%></td>
    <td><%= f.number_field :height%></td>
  </tr><tr>

    <td><%= f.label :goal_weight%></td>
    <td><%= f.number_field :goal%></td>
  </tr><tr>
    <td>


    <% if (@user.goal && @user.height) && @user.age
      maint = (66 + ( 6.23 * @user.weight) + ( 12.7 * @user.height ) - ( 6.8 * @user.age )) * 1.2
    end
    %>
    Your maintenance caloric needs are
  </td>
  <th>
    <%= maint.to_i %>
  </th>
  </tr>
    <tr>
      <td>

      <%= f.submit %></td>
  </tr>
  </table>

  

<% end %>
<br>
<%= link_to 'main',  "/" %>

<%= render "layouts/food" %>
<br>
<h3><%=@user.handle%> id: <%=@user.id%></h3>

app/views/users/index.html.erb
<div id="indexDiv">

<script>

<%
total_cals = 0
total_fat_cals = 0
total_carb_cals = 0
total_pro_cals = 0
if @foods
  @foods.each do |food|
    total_fat_cals += food.fat
    total_carb_cals += food.carbs
    total_pro_cals += food.protein
    total_cals += food.cals
  end
end
%>
var calPie = [0,0,0,100];
<%if total_cals > 0 %>
calPie = [<%= total_pro_cals %>,<%= total_carb_cals %>,<%= total_fat_cals %>];
<% end %>

</script>



<div id="side">

<span>Search for the food you wish to add</span><br>
    <input id="foodToFind" placeholder="food item"/>
      <button id="get"> SEARCH</button>
  <div id="menuContainer">
    <ul id="menu">

    </ul>
  </div>


    <div>

    <span>Amount in grams</span><input type="number" id="qty" placeholder="0" min="1">
    <button id="create">add food to diary</button></div>
    <div id="nutrionalInfo">
    </div>
</div>





    <div id="status">

      Daily calorie goal: <%= @user.target if @user%><br>
      Today's caloric intake: <%=total_cals%><br>
      remaining calories: <%= @user.target - total_cals if @user%>

    </div>
  <div id="svgContainer">

    <svg width="460" height = "400">
      <g class="legend" transform="translate(360,160)">
        <rect width="18" height="18" style="fill: #ff8c00; stroke: rgb(57, 59, 121);"></rect>
        <text x="22" y="14">Fat </text>
      </g>
      <g class="legend" transform="translate(360,190)">
        <rect width="18" height="18" style="fill: #a05d56; stroke: rgb(82, 84, 163);"></rect>
        <text x="22" y="14">Carbs</text>
      </g>
      <g class="legend" transform="translate(360,220)">
        <rect width="18" height="18" style="fill: #98abc5; stroke: rgb(107, 110, 207);"></rect>
        <text x="22" y="14">Protein</text>
      </g>


    </svg>
    <div id="calorimeter">
    </div>

    <div id="nutrionalInfo">

    </div>

  </div>

  <div id="foodReceived">

  <%= render "layouts/food" %>

</div>
<div id="bottom">


  <%= link_to 'Food Diary', food_journals_path + '?date=' + Date.today.to_s if @user %>
<br>
<%= link_to 'User Profile', edit_user_path(@user) if @user%>
</div>
</div>

app/views/users/new.html.erb
<h3>Register New User</h3>


<%= form_for @user, url: {action: 'create'} do |f|%>
<table>

<tr>


  <td><%= f.label :username%></td>
  <td><%= f.text_field :handle%></td>

</tr>
<tr>


<td><%= f.label :password%></td>

<td><%= f.password_field :password%></td>

</tr><tr>


  <td><%= f.radio_button(:male, true) %>
  <%= f.label(:gender_male, "Male")%></td>
  <td><%= f.radio_button(:male, false) %>
  <%= f.label(:gender_male, "Female")%></td>
</tr><tr>

  <td><%= f.label :age%></td>
  <td><%= f.number_field :age%></td>
</tr><tr>

  <td><%= f.label :weight%></td>
  <td><%= f.number_field :weight%></td>
</tr><tr>

  <td><%= f.label :target_calories%></td>
  <td><%= f.number_field :target%></td>
</tr><tr>

  <td><%= f.label :height_in_inches%></td>
  <td><%= f.number_field :height%></td>
</tr><tr>

  <td><%= f.label :goal_weight%></td>
  <td><%= f.number_field :goal%></td>
</tr><tr>

  <tr>
    <td>

    <%= f.submit %></td>
</tr>
</table>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>